openapi: 3.0.3
info:
  title: Backoffice API
  version: 1.0.0
paths:
  /api/login:
    post:
      summary: Obtain JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: JWT token
  /api/clients:
    get:
      summary: List clients
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Client list
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
